package com.balitech.balinote.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF6146C6)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE6DEFF)
val onPrimaryContainerLight = Color(0xFF1D1148)
val inversePrimaryLight = Color(0xFFCBBEFF)
val secondaryLight = Color(0xFFFF6157)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDAD6)
val onSecondaryContainerLight = Color(0xFF3B0907)
val tertiaryLight = Color(0xFFF6A23E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDDB7)
val onTertiaryContainerLight = Color(0xFF2A1700)
//val errorLight = Color(0xFFC00100)
//val onErrorLight = Color(0xFFFFFFFF)
//val errorContainerLight = Color(0xFFFFDAD4)
//val onErrorContainerLight = Color(0xFF410000)
val backgroundLight = Color(0xFFFDF8FF)
val onBackgroundLight = Color(0xFF1C1B20)
val surfaceLight = Color(0xFFFDF8FF)
val onSurfaceLight = Color(0xFF1C1B20)
val surfaceVariantLight = Color(0xFFE6E0EC)
val onSurfaceVariantLight = Color(0xFF48454E)
val inverseSurfaceLight = Color(0xFF312F36)
val inverseOnSurfaceLight = Color(0xFFF4EFF7)
val outlineLight = Color(0xFF79757F)
val outlineVariantLight = Color(0xFFC9C4D0)
val scrimLight = Color(0xFF000000)


val primaryDark = Color(0xFFCBBEFF)
val onPrimaryDark = Color(0xFF32285E)
val primaryContainerDark = Color(0xFF493E76)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val inversePrimaryDark = Color(0xFF615690)
val secondaryDark = Color(0xFFFFB4AC)
val onSecondaryDark = Color(0xFF690006)
val secondaryContainerDark = Color(0xFF900C12)
val onSecondaryContainerDark = Color(0xFFFFDAD6)
val tertiaryDark = Color(0xFFF7BC70)
val onTertiaryDark = Color(0xFF462A00)
val tertiaryContainerDark = Color(0xFF643F00)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
//val errorDark = Color(0xFFFFB4AC)
//val onErrorDark = Color(0xFF561E1A)
//val errorContainerDark = Color(0xFF73332E)
//val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141318)
val onBackgroundDark = Color(0xFFE6E1E9)
val surfaceDark = Color(0xFF141318)
val onSurfaceDark = Color(0xFFE6E1E9)
val surfaceVariantDark = Color(0xFF48454E)
val onSurfaceVariantDark = Color(0xFFC9C4D0)
val inverseSurfaceDark = Color(0xFFE6E1E9)
val inverseOnSurfaceDark = Color(0xFF312F36)
val outlineDark = Color(0xFF938F99)
val outlineVariantDark = Color(0xFF48454E)
val scrimDark = Color(0xFF000000)
